.TH SIPVPN 8 "Aug 04, 2015"
.SH NAME
sipvpn \- Simple stateless VPN

.SH SYNOPSIS
\fBsipvpn\fR [options...]

.SH DESCRIPTION
\fBsipvpn\fR is a simple stateless VPN.
.PP

.SH OPTIONS
.TP
.B \-h, \-\-help
print help message and exit
.TP
.B \-c, \-\-config \fI<file>\fR
config file
.TP
.B \-d, \-\-daemon
daemonize after startup
.TP
.B \-\-pidfile \fI<file>\fR
PID file
.TP
.B \-\-logfile \fI<file>\fR
log file
.TP
.B \-V, \-\-version
print version and exit


.SH CONFIG FILE

.TP
\fIuser=\fR
.br
user to set privilege to

.TP
\fImode=\fR
.br
server or client

.TP
\fIserver=\fR
.br
server address

.TP
\fIport=\fR
.br
server port, default: 1205

.TP
\fIkey=\fR
.br
secret key for crypto

.TP
\fItunif=\fR
.br
TUN device name, default: vpn0

.TP
\fImtu=\fR
.br
MTU of TUN device

.TP
\fIaddress=\fR
.br
IPv4 address of TUN device, CIDR notation, e.g. 10.10.10.0/31

.TP
\fIaddress6=\fR
.br
IPv6 address of TUN device, CIDR notation

.TP
\fIpeer=\fR
.br
IPv4 address of remote peer, e.g. 10.10.10.1 (darwin only)

.TP
\fIroute=\fR
.br
add route or not (used in client, yes or no)

.TP
\fInat=\fR
.br
enable NAT or not (used in server, yes or no)

.TP
\fIkeepalive=\fR
.br
interval for heartbeat, 0 means disabled (used in client)

.SH AUTHOR
.PP
This manual page was written by Xiaoxiao Pu <i@xiaoxiao.im>.
